// Mocks generated by Mockito 5.4.5 from annotations
// in todoist/test/use_case_test/time_tracking_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todoist/domain/model/time_tracking.dart' as _i4;
import 'package:todoist/domain/repository/time_tracking_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TimeTrackingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeTrackingRepository extends _i1.Mock
    implements _i2.TimeTrackingRepository {
  MockTimeTrackingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> updateTimeTracking(_i4.TaskTimeTracking? timeTracking) =>
      (super.noSuchMethod(
            Invocation.method(#updateTimeTracking, [timeTracking]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.TaskTimeTracking?> getTimeTrackingById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeTrackingById, [id]),
            returnValue: _i3.Future<_i4.TaskTimeTracking?>.value(),
          )
          as _i3.Future<_i4.TaskTimeTracking?>);

  @override
  _i3.Future<void> createTimeTracking(_i4.TaskTimeTracking? timeTracking) =>
      (super.noSuchMethod(
            Invocation.method(#createTimeTracking, [timeTracking]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
